### ISSUE TITLE
大佬救我，，

### ISSUE THREAD

**Issue by a370263995** [Water008/qqread#1]
我每次运行时都会出错，，，按着说明填的密匙，总会卡在<修复本地运行错误>这个文件夹，，

**Comment by Water008** [comment]
有截图吗？还有请把具体报错信息发上来，要不我也不知道什么情况啊

**Comment by qiaodgn** [comment]
不会抓包。。。

**Comment by a370263995** [comment]
- [ ] [](url)

> 有截图吗？还有请把具体报错信息发上来，要不我也不知道什么情况啊

是这样的，我三个密匙是这样填的，是不是错了？

> QQREADHEADERS
{"Cookie":"ywguid=370263995;ywkey=ywzn5tM43hbq;platform=android;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.18.4945;os_ver=Android 10;mpos_ver=1.21.0}

> QQREADTIMEHEADERS
{"Cookie":"ywguid=370263995;ywkey=ywzn5tM43hbq;platform=android;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.18.4945;os_ver=Android10;mpos_ver=1.21.0;platform=android;openid=8D67A752D9923136383B7D24C668B824}

> QQREADTIMEURL
https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=1011&refer=-1&bid=130833&readTime=8350&read_type=0&conttype=1&read_status=0&chapter_info=%5B%7B%221%22%3A%7B%22readTime%22%3A5522%2C%22pay_status%22%3A2%2C%22is_tail%22%3A1%7D%7D%2C%7B%222%22%3A%7B%22readTime%22%3A2828%2C%22pay_status%22%3A2%2C%22is_tail%22%3A1%7D%7D%5D&sp=-1

**Comment by Water008** [comment]
{"Cookie":"ywguid=370263995;ywkey=ywzn5tM43hbq;platform=android;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.18.4945;os_ver=Android 10;mpos_ver=1.21.0}
后面的引号不见啦
正确形式为
{"aaa":"bbb","ccc":ddd",........}

**Comment by Water008** [comment]
> * [ ]
> 
> > 有截图吗？还有请把具体报错信息发上来，要不我也不知道什么情况啊
> 
> 是这样的，我三个密匙是这样填的，是不是错了？
> 
> > QQREADHEADERS
> > {"Cookie":"ywguid=370263995;ywkey=ywzn5tM43hbq;platform=android;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.18.4945;os_ver=Android 10;mpos_ver=1.21.0}
> 
> > QQREADTIMEHEADERS
> > {"Cookie":"ywguid=370263995;ywkey=ywzn5tM43hbq;platform=android;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.18.4945;os_ver=Android10;mpos_ver=1.21.0;platform=android;openid=8D67A752D9923136383B7D24C668B824}
> 
> > QQREADTIMEURL
> > https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=1011&refer=-1&bid=130833&readTime=8350&read_type=0&conttype=1&read_status=0&chapter_info=%5B%7B%221%22%3A%7B%22readTime%22%3A5522%2C%22pay_status%22%3A2%2C%22is_tail%22%3A1%7D%7D%2C%7B%222%22%3A%7B%22readTime%22%3A2828%2C%22pay_status%22%3A2%2C%22is_tail%22%3A1%7D%7D%5D&sp=-1

{"Cookie":"ywguid=370263995;ywkey=ywzn5tM43hbq;platform=android;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.18.4945;os_ver=Android 10;mpos_ver=1.21.0}
后面的引号不见啦
正确形式为
{"aaa":"bbb","ccc":ddd",........}

**Comment by Water008** [comment]
> 不会抓包。。。

善用搜索。。。

**Comment by a370263995** [comment]
> > * [ ]
> > 
> > > 有截图吗？还有请把具体报错信息发上来，要不我也不知道什么情况啊
> > 
> > 
> > 是这样的，我三个密匙是这样填的，是不是错了？
> > > QQREADHEADERS
> > > {"Cookie":"ywguid=370263995;ywkey=ywzn5tM43hbq;platform=android;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.18.4945;os_ver=Android 10;mpos_ver=1.21.0}
> > 
> > 
> > > QQREADTIMEHEADERS
> > > {"Cookie":"ywguid=370263995;ywkey=ywzn5tM43hbq;platform=android;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.18.4945;os_ver=Android10;mpos_ver=1.21.0;platform=android;openid=8D67A752D9923136383B7D24C668B824}
> > 
> > 
> > > QQREADTIMEURL
> > > https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=1011&refer=-1&bid=130833&readTime=8350&read_type=0&conttype=1&read_status=0&chapter_info=%5B%7B%221%22%3A%7B%22readTime%22%3A5522%2C%22pay_status%22%3A2%2C%22is_tail%22%3A1%7D%7D%2C%7B%222%22%3A%7B%22readTime%22%3A2828%2C%22pay_status%22%3A2%2C%22is_tail%22%3A1%7D%7D%5D&sp=-1
> 
> {"Cookie":"ywguid=370263995;ywkey=ywzn5tM43hbq;platform=android;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.18.4945;os_ver=Android 10;mpos_ver=1.21.0}
> 后面的引号不见啦
> 正确形式为
> {"aaa":"bbb","ccc":ddd",........}

奥，我只补上最后一个双引号就好了吧？

**Comment by Water008** [comment]
> > > * [ ]
> > > 
> > > > 有截图吗？还有请把具体报错信息发上来，要不我也不知道什么情况啊
> > > 
> > > 
> > > 是这样的，我三个密匙是这样填的，是不是错了？
> > > > QQREADHEADERS
> > > > {"Cookie":"ywguid=370263995;ywkey=ywzn5tM43hbq;platform=android;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.18.4945;os_ver=Android 10;mpos_ver=1.21.0}
> > > 
> > > 
> > > > QQREADTIMEHEADERS
> > > > {"Cookie":"ywguid=370263995;ywkey=ywzn5tM43hbq;platform=android;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.18.4945;os_ver=Android10;mpos_ver=1.21.0;platform=android;openid=8D67A752D9923136383B7D24C668B824}
> > > 
> > > 
> > > > QQREADTIMEURL
> > > > https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=1011&refer=-1&bid=130833&readTime=8350&read_type=0&conttype=1&read_status=0&chapter_info=%5B%7B%221%22%3A%7B%22readTime%22%3A5522%2C%22pay_status%22%3A2%2C%22is_tail%22%3A1%7D%7D%2C%7B%222%22%3A%7B%22readTime%22%3A2828%2C%22pay_status%22%3A2%2C%22is_tail%22%3A1%7D%7D%5D&sp=-1
> > 
> > 
> > {"Cookie":"ywguid=370263995;ywkey=ywzn5tM43hbq;platform=android;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.18.4945;os_ver=Android 10;mpos_ver=1.21.0}
> > 后面的引号不见啦
> > 正确形式为
> > {"aaa":"bbb","ccc":ddd",........}
> 
> 奥，我只补上最后一个双引号就好了吧？

同步下最新代码，我做了点修改
