### ISSUE TITLE
获取cookie

### ISSUE THREAD

**Issue by doraevee** [Water008/qqread#10]
大佬怎么获取cookie啊 ，是不是只有水果机才能获取啊

**Comment by meselson** [comment]
> 大佬怎么获取cookie啊 ，是不是只有水果机才能获取啊

安卓可以，请自行搜索

**Comment by Water008** [comment]
> 大佬怎么获取cookie啊 ，是不是只有水果机才能获取啊

安卓可以，请自行搜索

**Comment by RockZhou8** [comment]
> > 大佬怎么获取cookie啊 ，是不是只有水果机才能获取啊
> 
> 安卓可以，请自行搜索

貌似PC装fiddler之类的才行，我还在学习，还没抓到

**Comment by doraevee** [comment]
> > > 大佬怎么获取cookie啊，是不是只有水果机才能获取啊
> > 
> > 
> > 安卓可以，请自行搜索
> 
> 貌似PC装fiddler之类的才行，我还在学习，还没抓到

抓到了，求教一下
