### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by qiaodgn** [Water008/qqread#11]
============开始运行第1个账号===========
Traceback (most recent call last):
  File "/root/qqread/qqread.py", line 339, in <module>
    start(index, secrets)
  File "/root/qqread/qqread.py", line 229, in start
    print(f"Track update {qqreadtrack(secrets[0], secrets[1])['msg']}")
  File "/root/qqread/qqread.py", line 177, in qqreadtrack
    data = re.sub(finddis.findall(data)[
IndexError: list index out of range

**Comment by qiaodgn** [comment]
是我的bodys填写错误吗？
qqreadbodys1 = '{"common" : {"appid" : 1450024394,"guid" : 772131492,"source" : "wza0005wzb0003","missions" : -1,"openid" : "894EB615C459FB0B07DB9BC4169AC89B","brand" : "iPhone","qq_ver" : "8.4.17","screenHeight" : 667,"windowHeight" : 618,"caseID" : -1,"areaid" : 5,"os_ver" : "iOS 13.7","session" : "vrnvw3xed67iay1sv43cvs1bq1nlt3uj","windowWidth" : 375,"model" : "iPhone 8Plus<iPhone10,2>","screenWidth" : 375,"hasRedDot" : "false",},"dataList" : [{"click1" "qqauthorize_addRCS_get_C","click2" : "topBar_left_back_C","eventID" : "qqauthorize_addRCS_succ_C","ext6" : 34,"dis" : 1607564626889,"type" : "click","refer" : "pages\/index\/index","route" : "pages\/book-read\/index","options" : {"bid" : "20909208" }}]}'

**Comment by Water008** [comment]
> 是我的bodys填写错误吗？
> qqreadbodys1 = '{"common" : {"appid" : 1450024394,"guid" : 772131492,"source" : "wza0005wzb0003","missions" : -1,"openid" : "894EB615C459FB0B07DB9BC4169AC89B","brand" : "iPhone","qq_ver" : "8.4.17","screenHeight" : 667,"windowHeight" : 618,"caseID" : -1,"areaid" : 5,"os_ver" : "iOS 13.7","session" : "vrnvw3xed67iay1sv43cvs1bq1nlt3uj","windowWidth" : 375,"model" : "iPhone 8Plus<iPhone10,2>","screenWidth" : 375,"hasRedDot" : "false",},"dataList" : [{"click1" "qqauthorize_addRCS_get_C","click2" : "topBar_left_back_C","eventID" : "qqauthorize_addRCS_succ_C","ext6" : 34,"dis" : 1607564626889,"type" : "click","refer" : "pages/index/index","route" : "pages/book-read/index","options" : {"bid" : "20909208" }}]}'

你把bodys里的空格全删了就可以了

**Comment by Water008** [comment]
> 是我的bodys填写错误吗？
> qqreadbodys1 = '{"common" : {"appid" : 1450024394,"guid" : 772131492,"source" : "wza0005wzb0003","missions" : -1,"openid" : "894EB615C459FB0B07DB9BC4169AC89B","brand" : "iPhone","qq_ver" : "8.4.17","screenHeight" : 667,"windowHeight" : 618,"caseID" : -1,"areaid" : 5,"os_ver" : "iOS 13.7","session" : "vrnvw3xed67iay1sv43cvs1bq1nlt3uj","windowWidth" : 375,"model" : "iPhone 8Plus<iPhone10,2>","screenWidth" : 375,"hasRedDot" : "false",},"dataList" : [{"click1" "qqauthorize_addRCS_get_C","click2" : "topBar_left_back_C","eventID" : "qqauthorize_addRCS_succ_C","ext6" : 34,"dis" : 1607564626889,"type" : "click","refer" : "pages/index/index","route" : "pages/book-read/index","options" : {"bid" : "20909208" }}]}'

已修改代码，你不用修改你的body了，请重新clone

**Comment by qiaodgn** [comment]
感谢 已解决
