### ISSUE TITLE
请问大佬，github上看着正常，打开手机上看到的历史金币历史都是1金币怎么办？

### ISSUE THREAD

**Issue by keysnick** [Water008/qqread#12]
请问大佬，手机端上看到的是1金币怎么办？

**Comment by Water008** [comment]
> 请问大佬，手机端上看到的是1金币怎么办？

你的body有问题吧

**Comment by Water008** [comment]
> 请问大佬，手机端上看到的是1金币怎么办？

类似于这样的参数
{"common":{"appid":***,"areaid":5,"qq_ver":"8.4.18.4945","os_ver":"Android 10","mp_ver":"0.31.0","mpos_ver":"1.21.0","brand":"***","model":"***","screenWidth":393,"screenHeight":816,"windowWidth":393,"windowHeight":762,"openid":"***","guid":***,"session":"***","scene":1023,"source":-1,"hasRedDot":"false","missions":-1,"caseID":-1},"dataList":[{"click1":"bookShelf_myshelf_myBook_C","click2":"qqauthorize_addRCS_succ_C","route":"pages/book-read/index","refer":"pages/book-shelf/index","options":{"bid":"27325720","cid":"3","from":"shelf"},"dis":1607325831391,"ext6":31,"eventID":"bookRead_show_I","type":"shown","ccid":3,"bid":"27325720","bookStatus":1,"bookPay":1,"chapterStatus":0,"ext1":{"font":18,"bg":0,"pageMode":1},"from":"bookShelf_myshelf_myBook_C_0_27325720"}]}

里面必须有bid，且bid要与QQREADTIMEURL里的bid一致

**Comment by keysnick** [comment]
我又仔细查了一下手机端的记录，从我上次提现以后，就开始一金币了，然后昨晚手动看了十分钟左右的书，手动领了金币，今天起床再看手机端，发现金币又正常了。
谢谢大佬百忙之中的回复。
