### ISSUE TITLE
执行py文件报错了

### ISSUE THREAD

**Issue by ZHonry** [Water008/qqread#13]
![image](https://user-images.githubusercontent.com/22869840/101804305-6734d100-3b4c-11eb-94a3-836b4d1baab1.png)
求教大佬，这个是什么原因报错的？三个参数已经根示例核对了好多次了。实在没折了

**Comment by Water008** [comment]
> ![image](https://user-images.githubusercontent.com/22869840/101804305-6734d100-3b4c-11eb-94a3-836b4d1baab1.png)
> 求教大佬，这个是什么原因报错的？三个参数已经根示例核对了好多次了。实在没折了

你把headers发上来我看看

**Comment by ZHonry** [comment]
> > ![图片](https://user-images.githubusercontent.com/22869840/101804305-6734d100-3b4c-11eb-94a3-836b4d1baab1.png)
> > 求教大佬，这个是什么原因报错的？三个参数已经根示例核对了好多次了。实在没折了
> 
> 你把headers发上来我看看

qqreadheaders1 = '{"ywsession":"il93zcfg7i42ik5tq67z71uxc9ypohj5","Cookie":"ywguid=309757822;ywkey=ywmm7jl23kDA;platform=ios;channel=mqqmina;mpVersion=0.33.3;qq_ver=8.4.17;os_ver=iOS 14.2;mpos_ver=1.21.0","Connection":"keep-alive","Content-Type":"application/json","Accept":"*/*","Host":"mqqapi.reader.qq.com","User-Agent":"QQ/8.4.17.638 CFNetwork/1206 Darwin/20.1.0","Referer":"https://appservice.qq.com/1110657249/0.32.5/page-frame.html","Accept-Language":"zh-cn","Accept-Encoding":"gzip","mpversion":"0.33.3"}'
#qqreadheaders2 = '{}'

**Comment by nxppru** [comment]
少了一个英文半角逗号，"mpversion":"0.33.3",}'

**Comment by Water008** [comment]
> > > ![图片](https://user-images.githubusercontent.com/22869840/101804305-6734d100-3b4c-11eb-94a3-836b4d1baab1.png)
> > > 求教大佬，这个是什么原因报错的？三个参数已经根示例核对了好多次了。实在没折了
> > 
> > 
> > 你把headers发上来我看看
> 
> qqreadheaders1 = '{"ywsession":"il93zcfg7i42ik5tq67z71uxc9ypohj5","Cookie":"ywguid=309757822;ywkey=ywmm7jl23kDA;platform=ios;channel=mqqmina;mpVersion=0.33.3;qq_ver=8.4.17;os_ver=iOS 14.2;mpos_ver=1.21.0","Connection":"keep-alive","Content-Type":"application/json","Accept":"_/_","Host":"mqqapi.reader.qq.com","User-Agent":"QQ/8.4.17.638 CFNetwork/1206 Darwin/20.1.0","Referer":"[https://appservice.qq.com/1110657249/0.32.5/page-frame.html","Accept-Language":"zh-cn","Accept-Encoding":"gzip","mpversion":"0.33.3"}](https://appservice.qq.com/1110657249/0.32.5/page-frame.html%22,%22Accept-Language%22:%22zh-cn%22,%22Accept-Encoding%22:%22gzip%22,%22mpversion%22:%220.33.3%22%7D)'
> #qqreadheaders2 = '{}'

把 ,"Accept":"/" 删了，再手动进入一下小程序，阅读以下随意一本书就好了
