### ISSUE TITLE
抓取的cooie参数格式不一样

### ISSUE THREAD

**Issue by chihwell** [Water008/qqread#15]
大佬，我抓取的参数格式似乎不一样

**Comment by Water008** [comment]
> 大佬，我抓取的参数格式似乎不一样

光说一句不一样，我怎么知道怎么不一样？

**Comment by keysnick** [comment]
> 大佬，我抓取的参数格式似乎不一样
抓取的参数格式不一样，一定是你抓错了，我就是按照大佬的方法抓成功的
