### ISSUE TITLE
fiddler抓cookie

### ISSUE THREAD

**Issue by doraevee** [Water008/qqread#17]
大佬用fiddler抓到这样的cookie对吗？
Cookie: ywguid=740322245;ywkey=ywFdAjdwXHfa;platform=android;channel=mqqmina;mpVersion=0.33.3;qq_ver=8.4.18.4945;os_ver=Android 9;mpos_ver=1.21.0

**Comment by Water008** [comment]
> 大佬用fiddler抓到这样的cookie对吗？
> Cookie: ywguid=740322245;ywkey=ywFdAjdwXHfa;platform=android;channel=mqqmina;mpVersion=0.33.3;qq_ver=8.4.18.4945;os_ver=Android 9;mpos_ver=1.21.0

headers要把全部信息写上，不仅仅是cookie

**Comment by doraevee** [comment]
> > 大佬用提琴手抓到这样的饼干对吗？
> > 曲奇：ywguid = 740322245; ywkey = ywFdAjdwXHfa;平台=机器人;信道= mqqmina; mpVersion = 0.33.3; qq_ver = 8.4.18.4945; os_ver = Android的9; mpos_ver = 1.21 .0
> 
> 标头要放全部信息写上，多个cookie

终于可以了 谢谢大佬
