### ISSUE TITLE
请问群晖运行出现这个是怎么回事啊

### ISSUE THREAD

**Issue by mengdie101** [Water008/qqread#18]
File "/volume1/web/python/qqread/qqread.py", line 58
    functionURL = f"https://mqqapi.reader.qq.com/mqq/{functionId}"
                                                                 ^
SyntaxError: invalid syntax

**Comment by Water008** [comment]
> File "/volume1/web/python/qqread/qqread.py", line 58
> functionURL = f"[https://mqqapi.reader.qq.com/mqq/{functionId}](https://mqqapi.reader.qq.com/mqq/%7BfunctionId%7D)"
> ^
> SyntaxError: invalid syntax

python版本过低，不支持f-string，请升级python
