### ISSUE TITLE
这个错误是啥原因啊

### ISSUE THREAD

**Issue by a370263995** [Water008/qqread#2]
KeyError: 'todayReadSeconds'
Error: Process completed with exit code 1.

**Comment by xiaokaig** [comment]
我也是

**Comment by Water008** [comment]
> KeyError: 'todayReadSeconds'
> Error: Process completed with exit code 1.

首先，同步最新代码，要是还报错，检查第二个账号的各参数是否有误

**Comment by a370263995** [comment]
> > KeyError: 'todayReadSeconds'
> > Error: Process completed with exit code 1.
> 
> 首先，同步最新代码，要是还报错，检查第二个账号的各参数是否有误

现在1个账号成这样了
TypeError: 'NoneType' object is not subscriptable
Error: Process completed with exit code ***.
三个参数是这样填的

> {"Cookie":"ywguid=370263995;ywkey=ywzn5tM43hbq;platform=android;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.18.4945;os_ver=Android 10;mpos_ver=1.21.0"}

> {"Cookie":"ywguid=370263995;ywkey=ywzn5tM43hbq;platform=android;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.18.4945;os_ver=Android10;mpos_ver=1.21.0;platform=android;openid=8D67A752D9923136383B7D24C668B824"}


> https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=3001&refer=-1&bid=131732&readTime=18455&read_type=0&conttype=1&read_status=0&chapter_info=%5B%7B%221%22%3A%7B%22readTime%22%3A18455%2C%22pay_status%22%3A2%7D%7D%5D&sp=-1

**Comment by Water008** [comment]
> > > KeyError: 'todayReadSeconds'
> > > Error: Process completed with exit code 1.
> > 
> > 
> > 首先，同步最新代码，要是还报错，检查第二个账号的各参数是否有误
> 
> 现在1个账号成这样了
> TypeError: 'NoneType' object is not subscriptable
> Error: Process completed with exit code ***.
> 三个参数是这样填的
> 
> > {"Cookie":"ywguid=370263995;ywkey=ywzn5tM43hbq;platform=android;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.18.4945;os_ver=Android 10;mpos_ver=1.21.0"}
> 
> > {"Cookie":"ywguid=370263995;ywkey=ywzn5tM43hbq;platform=android;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.18.4945;os_ver=Android10;mpos_ver=1.21.0;platform=android;openid=8D67A752D9923136383B7D24C668B824"}
> 
> > https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=3001&refer=-1&bid=131732&readTime=18455&read_type=0&conttype=1&read_status=0&chapter_info=%5B%7B%221%22%3A%7B%22readTime%22%3A18455%2C%22pay_status%22%3A2%7D%7D%5D&sp=-1

下午帮你看下

**Comment by a370263995** [comment]
> > > > KeyError：“ todayReadSeconds”
> > > > 错误：进程已完成，退出代码为1。
> > > 
> > > 
> > > 首先，同步最新代码，要是还报错，检查第二个账号的各参数是否有误
> > 
> > 
> > 现在1个账号成成这样了
> > TypeError：'NoneType'对象不可下标
> > 错误：进程已完成，退出代码为***。
> > 三个参数是这样填的
> > > {“ Cookie”：“ ywguid = 370263995; ywkey = ywzn5tM43hbq; platform = android; channel = mqqmina; mpVersion = 0.30.0; qq_ver = 8.4.18.4945; os_ver = Android 10; mpos_ver = 1.21.0“}
> > 
> > 
> > > {“ Cookie”：“ ywguid = 370263995; ywkey = ywzn5tM43hbq; platform = android; channel = mqqmina; mpVersion = 0.30.0; qq_ver = 8.4.18.4945; os_ver = Android10; mpos_ver = 1.21.0; platform = android; openid = 8D67A752D9923136383B7D24C668B824“}
> > 
> > 
> > > [https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=3001&refer=-1&bid=131732&readTime=18455&read_type=0&conttype=1&read_status=0&chapter_info=%5B%7B%221%22%3A%7B%22readTime%22% 3A18455％2C％22pay_status％22％3A2％7D％7D％5D＆sp = -1](https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=3001&refer=-1&bid=131732&readTime=18455&read_type=0&conttype=1&read_status=0&chapter_info=%5B%7B%221%22%3A%7B%22readTime%22%3A18455%2C%22pay_status%22%3A2%7D%7D%5D&sp=-1)
> 
> 下午帮你看下

麻烦了呀，谢谢大佬了

**Comment by Water008** [comment]
> 我也是

你的时间上传url有问题吧

**Comment by a370263995** [comment]
> > 我也是
> 
> 你的时间上传url有问题吧

我要重新上传一遍第三个，就是那个url网址嘛？

**Comment by a370263995** [comment]
> > 我也是
> 
> 你的时间上传url有问题吧

我是不是得重新抓一下url包啊

**Comment by a370263995** [comment]
错误是这样的
TypeError: 'NoneType' object is not subscriptable
Error: Process completed with exit code ***.

**Comment by Water008** [comment]
> 错误是这样的
> TypeError: 'NoneType' object is not subscriptable
> Error: Process completed with exit code ***.

已修复，请重新同步代码即可

**Comment by Water008** [comment]
> > > KeyError: 'todayReadSeconds'
> > > Error: Process completed with exit code 1.
> > 
> > 
> > 首先，同步最新代码，要是还报错，检查第二个账号的各参数是否有误
> 
> 现在1个账号成这样了
> TypeError: 'NoneType' object is not subscriptable
> Error: Process completed with exit code ***.
> 三个参数是这样填的
> 
> > {"Cookie":"ywguid=..........;ywkey=.........;platform=android;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.18.4945;os_ver=Android 10;mpos_ver=1.21.0"}
> 
> > {"Cookie":"ywguid=........;ywkey=..........;platform=android;channel=mqqmina;mpVersion=0.30.0;qq_ver=8.4.18.4945;os_ver=Android10;mpos_ver=1.21.0;platform=android;openid=............."}
> 
> > https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=3001&refer=-1&bid=131732&readTime=18455&read_type=0&conttype=1&read_status=0&chapter_info=%5B%7B%221%22%3A%7B%22readTime%22%3A18455%2C%22pay_status%22%3A2%7D%7D%5D&sp=-1

帮你把三个参数编辑掉了
