### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Hello-XPH** [Water008/qqread#20]
## 1. 关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ *] 没有类似的issue 

Q：是否仔细阅读了教程
- [* ] 已仔细阅读教程 

## 2. 你使用的哪种运行方案

- [* ] 方法一：GitHub action自动运行 
- [ ] 方法二：本地运行

### (1) 具体问题
A：发现没有运行打开看的

### (2) 详细日志(如果是GitHub action运行，请附上具体网址)
A：
![image](https://user-images.githubusercontent.com/56664327/102685403-42f78500-421b-11eb-8fde-105207df3fe4.png)

![image](https://user-images.githubusercontent.com/56664327/102685453-a5508580-421b-11eb-81b1-cb10b1f82b75.png)

**Comment by Hello-XPH** [comment]
@Water008

**Comment by Water008** [comment]
转为public就好

**Comment by Hello-XPH** [comment]
私人不行吗?

**Comment by Hello-XPH** [comment]
问题是之前私人,也可以运行啊

**Comment by 1997108** [comment]
一天天哔哔 烦死人了 多研究下不行吗

**Comment by Water008** [comment]
> 问题是之前私人,也可以运行啊

限额超了，明白？想继续私人，你充值github吧

**Comment by Hello-XPH** [comment]
ok,明白了.谢谢
