### ISSUE TITLE
请问显示各项secres数量不符是为什么？[BUG]

### ISSUE THREAD

**Issue by Wake326** [Water008/qqread#21]
## 1. 关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种运行方案

- [ x] 方法一：GitHub action自动运行 
- [ ] 方法二：本地运行

### (1) 具体问题
A：显示各项secres数量不符
![image](https://user-images.githubusercontent.com/60837978/102704203-37579d00-42b3-11eb-8a47-50e68170300f.png)

我的各项secert设置：
1、{"Cookie":"ywguid=XXXXX;ywkey=XXXXXXX;platform=android;channel=mqqmina;mpVersion=0.35.3;qq_ver=8.4.18.4945;os_ver=Android10;mpos_ver=1.21.0;platform=android;openid=35EE36E87D31C7AE109C06296ADD36DB",Referer":"https://appservice.qq.com/1110657249/0.35.3/page-frame.html","User-Agent":"Mozilla%2F5.0+%28Linux%3B+Android+10%3B+ALP-AL00+Build%2FHUAWEIALP-AL00%3B+wv%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Version%2F4.0+Chrome%2F83.0.4103.106+Mobile+Safari%2F537.36QQ/8.4.18.4945V1_AND_SQ_8.4.18_1558_YYB_DQQ/MiniApp","mpVersion":"0.35.3","content-type":"application/json","YwSession":"oydckzg0pnivsgvg0mwsxijrknwpklur","Host":"mqqapi.reader.qq.com","Connection":"Keep-Alive","Accept-Encoding":"gzip"}

2、{"common":{"appid":1450024393,"areaid":5,"qq_ver":"8.4.18.4945","os_ver":"Android10","mp_ver":"0.35.3","mpos_ver":"1.21.0","brand":"HUAWEI","model":"ALP-AL00","screenWidth":360,"screenHeight":640,"windowWidth":360,"windowHeight":640,"openid":"35EE36E87D31C7AE109C06296ADD36DB","guid":XXXXXXXXX,"session":"6h76t25jitl0rz03ppyvsy23d88ccgk2","scene":1043,"source":"wza0005wzb0003","hasRedDot":"false","missions":-1,"caseID":-1},"dataList":[{"click1":"push_limitNo_empowerSucSuc_C","click2":"push_limitNo_empowerSuc_C","route":"pages/book-read/index","refer":-1,"options":{"bid":"20909208","source":"wza0005wzb0003","fromGuid":"51530556","shareType":"303"},"dis":1608427574783,"ext6":8,"eventID":"onShow_O","type":"others","ui_pos":1,"scene":1043}]}

3、https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=1043&refer=-1&bid=20909208&readTime=11847&read_type=0&conttype=1&read_status=0&chapter_info=%5B%7B%222%22%3A%7B%22readTime%22%3A2812%2C%22pay_status%22%3A0%2C%22is_tail%22%3A1%7D%7D%2C%7B%223%22%3A%7B%22readTime%22%3A9035%2C%22pay_status%22%3A0%2C%22is_tail%22%3A0%7D%7D%5D&sp=-1

### (2) 详细日志(如果是GitHub action运行，请附上具体网址)
A：https://github.com/Wake326/qqread/runs/1583394411?check_suite_focus=true

**Comment by Water008** [comment]
请删除多余空行，几个账号就是几行

**Comment by Wake326** [comment]
只有一个账号，格式就空行问题，其他没有问题吧？

**Comment by Wake326** [comment]
删除空行后出现这样的问题：
Traceback (most recent call last):
  File "qqread.py", line 367, in <module>
    start(index, secrets)
  File "qqread.py", line 255, in start
    todaytime_data = qqreadtodaytime(secrets[0], secrets[2])
  File "qqread.py", line ***48, in qqreadtodaytime
    todaytime_data = getTemplate(headers, f"page/config?router=%2Fpages%2Fbook-read%2Findex&options=%7B%22bid%22%3A%22{bid}%22%7D")[
KeyError: 'todayReadSeconds'
Error: Process completed with exit code ***.。

地址：https://github.com/Wake326/qqread/runs/1583600946?check_suite_focus=true

**Comment by Water008** [comment]
> 删除空行后出现这样的问题：
> Traceback (most recent call last):
> File "qqread.py", line 367, in
> start(index, secrets)
> File "qqread.py", line 255, in start
> todaytime_data = qqreadtodaytime(secrets[0], secrets[2])
> File "qqread.py", line ***48, in qqreadtodaytime
> todaytime_data = getTemplate(headers, f"page/config?router=%2Fpages%2Fbook-read%2Findex&options=%7B%22bid%22%3A%22{bid}%22%7D")[
> KeyError: 'todayReadSeconds'
> Error: Process completed with exit code ***.。
> 
> 地址：https://github.com/Wake326/qqread/runs/1583600946?check_suite_focus=true

自己打开小程序读一会儿书就好了
