### ISSUE TITLE
[BUG]Repo-Setting-Secrets在哪呢

### ISSUE THREAD

**Issue by banxiu** [Water008/qqread#22]
## 1. 关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否仔细阅读了教程
- [x ] 已仔细阅读教程 

## 2. 你使用的哪种运行方案

- [ x] 方法一：GitHub action自动运行 
- [ ] 方法二：本地运行

### (1) 具体问题
A：
Repo-Setting-Secrets没找到这个配置  就在yml里看到了获取他的值

### (2) 详细日志(如果是GitHub action运行，请附上具体网址)
A：

**Comment by Water008** [comment]
请自行搜索
