### ISSUE TITLE
[BUG] todayReadSeconds 报错

### ISSUE THREAD

**Issue by Lich3nbo** [Water008/qqread#26]
## 1. 关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x ] 没有类似的issue 
看了好像都没有发现我这个问题
Q：是否仔细阅读了教程
- [ x ] 已仔细阅读教程 

## 2. 你使用的哪种运行方案

- [ x ] 方法一：GitHub action自动运行 
- [ ] 方法二：本地运行

### (1) 具体问题
A：
![image](https://user-images.githubusercontent.com/27914486/103099236-95d0a280-4648-11eb-86be-10d99807a7de.png)
header是根据 issuse 13 去配置的 把他的header 拿了出来 然后 去json.cn 一个一个值去 替换的

{"ywsession":"l779kuquelvd0su2qux7q2e7eush5l15","Cookie":"ywguid=361919253;ywkey=ywcAjnNTCBYT;platform=android;channel=mqqmina;mpVersion=0.38.1;qq_ver=8.5.0.5025;os_ver=Android10;mpos_ver=1.23.0;platform=android;openid=361919253","Connection":"keep-alive","Content-Type":"application/json","Host":"mqqapi.reader.qq.com","User-Agent":"Mozilla%2F5.0+%28Linux%3B+Android+10%3B+TAS-AN00+Build%2FHUAWEITAS-AN00%3B+wv%29+AppleWebKit%2F537.36+%28KHTML%2C+like+Gecko%29+Version%2F4.0+Chrome%2F78.0.3904.108+Mobile+Safari%2F537.36 QQ/8.5.0.5025 V1_AND_SQ_8.5.0_1596_YYB_D QQ/MiniApp","Referer":"https://appservice.qq.com/1110657249/0.38.1/page-frame.html","Accept-Language":"zh-cn","Accept-Encoding":"gzip","mpversion":"0.38.1"}

### (2) 详细日志(如果是GitHub action运行，请附上具体网址)
A：https://github.com/Lich3nbo/qqread/actions

**Comment by Water008** [comment]
自己进小程序看一会儿书就好了

**Comment by Lich3nbo** [comment]
> 自己进小程序看一会儿书就好了

qq小程序也可以吗
