### ISSUE TITLE
第一次运行成功 第二次运行报错

### ISSUE THREAD

**Issue by qiaodgn** [Water008/qqread#3]
============开始运行第1个账号===========
Traceback (most recent call last):
  File "/root/qqread/qqread.py", line 270, in <module>
    main()
  File "/root/qqread/qqread.py", line 222, in main
    if todaygift_data['amount'] > 0:
TypeError: 'NoneType' object is not subscriptable

**Comment by a370263995** [comment]
一样一样

**Comment by Water008** [comment]
> ============开始运行第1个账号===========
> Traceback (most recent call last):
> File "/root/qqread/qqread.py", line 270, in
> main()
> File "/root/qqread/qqread.py", line 222, in main
> if todaygift_data['amount'] > 0:
> TypeError: 'NoneType' object is not subscriptable

已修复，请重新同步代码即可
