### ISSUE TITLE
这错误是抓的包不对吗

### ISSUE THREAD

**Issue by xiaokaig** [Water008/qqread#4]
![IMG_20201203_140140](https://user-images.githubusercontent.com/39553056/100972478-d8381f80-3573-11eb-891b-610a22f14720.jpg)
这是填的不对吗

**Comment by Water008** [comment]
> ![IMG_20201203_140140](https://user-images.githubusercontent.com/39553056/100972478-d8381f80-3573-11eb-891b-610a22f14720.jpg)
> 这是填的不对吗

上传时间url填写有问题

**Comment by a370263995** [comment]
> > ![IMG_20201203_140140](https://user-images.githubusercontent.com/39553056/100972478-d8381f80-3573-11eb-891b-610a22f14720.jpg)
> > 这是填的不对吗
> 
> 上传时间url填写有问题

怎么填写上传url啊？

**Comment by xiaokaig** [comment]
> > ![IMG_20201203_140140](https://user-images.githubusercontent.com/39553056/100972478-d8381f80-3573-11eb-891b-610a22f14720.jpg)
> > 这是填的不对吗
> 
> 上传时间url填写有问题

https://mqqapi.reader.qq.com/mqq/addReadTimeWithBid?scene=3001&refer=-1&bid=126677&readTime=2200&read_type=0&conttype=1&read_status=0&chapter_info=%5B%7B%221%22%3A%7B%22readTime%22%3A2200%2C%22pay_status%22%3A0%7D%7D%5D&sp=-1


大佬给看下哪不对(~_~;)

**Comment by xiaokaig** [comment]
> > ![IMG_20201203_140140](https://user-images.githubusercontent.com/39553056/100972478-d8381f80-3573-11eb-891b-610a22f14720.jpg)
> > 这是填的不对吗
> 
> 上传时间url填写有问题

弄好了，大佬🤣弄了半天是名字少打一个字母
