### ISSUE TITLE
获取cookie、qqreadheaderVal等信息怎么获取

### ISSUE THREAD

**Issue by thisPunk** [Water008/qqread#5]
我使用httpcanary工具没有获取到啊，有教程嘛

**Comment by Water008** [comment]
> 我使用httpcanary工具没有获取到啊，有教程嘛

android7开始只信任系统根证书，不信任用户根证书，要么root，要么你找安卓7以下环境抓

**Comment by thisPunk** [comment]
...后来找的pj版，应该可以获取吧，但不知道怎么在抓包信息中搜索关键字，QQREADTIMEURL 可以搜索“addReadTimeWithBid”获取，QQREADHEADERS QQREADTIMEHEADERS这两个不知道有啥关键字。你的说明文档是不是用ios的工具获取啊

**Comment by Water008** [comment]
> ...后来找的pj版，应该可以获取吧，但不知道怎么在抓包信息中搜索关键字，QQREADTIMEURL 可以搜索“addReadTimeWithBid”获取，QQREADHEADERS QQREADTIMEHEADERS这两个不知道有啥关键字。你的说明文档是不是用ios的工具获取啊

headers，你搜索下什么是headers
