### ISSUE TITLE
请问大佬这是什么情况啊

### ISSUE THREAD

**Issue by Zing-Song** [Water008/qqread#7]
按照教程一步步来的，结果搞完每次运行都是这个样子
重新获取了cookie和url也是这样子
小白一个。。。实在是不会搞了
请大佬指点
<img width="1099" alt="截屏2020-12-06 17 41 21" src="https://user-images.githubusercontent.com/73926846/101276821-a2e93700-37ea-11eb-9ef0-059e458137cb.png">

**Comment by Water008** [comment]
请检查headers填写是否正确
